### ISSUE TITLE
Tracing the data

### ISSUE THREAD

**Issue by kuntzer** [megalut/megalut#150]
I'm trying to back-trace some galaxies from their `groupmeascat_cases` catalogues. With little success I might add. It looks like the file names and the real pixel positions are lost. It's bad for debugging.

I'm trying to think of a simple and efficient way of doing this.

**Comment by mtewes** [comment]
Yes, I see this point. The aim of grouping is to prepare a "small" and compact catalogue for the training. Maybe it's just not the place to trace galaxies. But it's easy to do this on a simple single-realization one-image-file catalog.

**Comment by kuntzer** [comment]
Okay, I have a working work around that does not change any thing in the MegaLUT code. It's kind of slow however, but it's working. I'm building a catalogue of the observations from the filenames which contain the name of the image and some unique property (say tru_s1). Then when searching for the file name I do an inverse search for the same (or most similar tru_s1).

**Comment by kuntzer** [comment]
No point in keeping this open. Re-open if necessary.
